services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./db/:/app/db/
      - ./configs/:/app/config/
    network_mode: "host"
  web:
    build: ./web
    ports:
      - "80:80"