apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app.kubernetes.io/name: api
spec:
  containers:
    - name: api
      image: clipboard-share-api:0.3.0
      ports:
        - containerPort: 8080
          name: http-api-svc
      env:
        - name: APP_DB_HOST
          value: "host.minikube.internal"
        - name: APP_CORS_ALLOW_ORIGINS
          value: "http://clipboard-share.home"
        - name: APP_COOKIE_DOMAIN
          value: "clipboard-share.home"
        - name: APP_JWT_AUDIENCE
          value: "api.clipboard-share.home"
        - name: APP_REDIS_ADDR
          value: "host.minikube.internal:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-api-svc
  type: NodePort
